name: mph-table
URL: https://github.com/indeedeng/mph-table.git
checkoutID: dbd5413df33bf8f0a995822eeefe94df50f3c5a7
patchName: artifacts/configs/mph-table/mph-table.patch
properties:
  - name: TestSmartListSerializer#canRoundTripSerializableLists
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableLists(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
  - name: TestSmartListSerializer#canRoundTripSerializableListsWithGenerator
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableListsWithGenerator(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
  - name: TestSmartShortSerializer#canRoundTripShort
    entryPoint: "com.indeed.mph.serializers.TestSmartShortSerializer.canRoundTripShort(S)V"
  - name: TestSmartIntegerSerializer#canRoundTripIntegers
    entryPoint: "com.indeed.mph.serializers.TestSmartIntegerSerializer.canRoundTripIntegers(I)V"
  - name: TestSmartStringSerializer#canRoundTripStrings
    entryPoint: "com.indeed.mph.serializers.TestSmartStringSerializer.canRoundTripStrings(Ljava/lang/String;)V"
  - name: TestSmartByteSerializer#canRoundTripBytes
    entryPoint: "com.indeed.mph.serializers.TestSmartByteSerializer.canRoundTripBytes(B)V"
  - name: TestSmartLongSerializer#canRoundTripLongs
    entryPoint: "com.indeed.mph.serializers.TestSmartLongSerializer.canRoundTripLongs(J)V"
  - name: TestSmartPairSerializer#canRoundTripPairs
    entryPoint: "com.indeed.mph.serializers.TestSmartPairSerializer.canRoundTripPairs(Lcom/indeed/util/core/Pair;)V"
  - name: TestSmartListSerializer#canRoundTripSerializableLists
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableLists(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
  - name: TestSmartListSerializer#canRoundTripSerializableListsWithGenerator
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableListsWithGenerator(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
  - name: TestSmartShortSerializer#canRoundTripShort
    entryPoint: "com.indeed.mph.serializers.TestSmartShortSerializer.canRoundTripShort(S)V"

